### ISSUE TITLE
java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0

### ISSUE THREAD

**Issue by wyatt8740** [ShivamMistry/RSLoader#2]
Upon launching the client for Old-School Runescape:
```
0.819672131147541
javaError: bh.<init>() bf.ah() | SampleModel:126 SinglePixelPackedSampleModel:144 SinglePixelPackedSampleModel:110 PackedColorModel:310 bh:28 bf:301 bf:341 Thread:748 | java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0
error_game_crash
http://oldschool5.runescape.com/error_game_crash.ws
_self
```

**Comment by Meegul** [comment]
I believe this issue might not be due to the loader. I've been trying to write a loader myself, and ran into this issue. After finding 2-3 other open source loaders, they all exhibit the same error. Perhaps it's Jagex's doing.

**Comment by wyatt8740** [comment]
One client that does not do this is this one: https://github.com/RuneSuite/simple-client

It's written in Kotlin, which is compiled for execution in a Java VM, like Scala. [There was a commit to fix this problem, too](https://github.com/RuneSuite/simple-client/commit/3e842711c6143b9f46c52d7b5c9271ff20c9d71c). It looks like they made the launcher call the init() and start() methods later on in the code than it had been executing.

I can confirm it works, although setting up a Kotlin compiler was quite annoying for me, and I had to tweak an XML file's version number (I forget which one) to make it build happily.

It's definitely Jagex's doing, but it's not anything actually showing any intent to stop unofficial clients.
It's just a change in their applet.

**Comment by Eimhym** [comment]
The easiest fix is to move applet.init() in RSLoader.java just before applet.start() line.

**Comment by ShivamMistry** [comment]
Hey, thanks for reporting this - apologies for the slow update but it should now be fixed :)

**Comment by wyatt8740** [comment]
No problem. I was curious as to what you'd do to fix it - I tried to interpret that kotlin implementation into your Java code, but was having a hard time wrapping my head around it.
Thanks for fixing it!
