### ISSUE TITLE
Loading no longer

### ISSUE THREAD

**Issue by ghostcam** [ShivamMistry/RSLoader#3]
Hi I have been using your code for a year now on a test project and never took the time to understand what's actually going on but it has always worked and I hacked it to load only old school.

Always receiving the following error:
Error: ba.<init>() bp.u() | java.awt.image.SampleModel.<init> java.awt.image.SinglePixelPackedSampleModel.<init> java.awt.image.SinglePixelPackedSampleModel.<init> java.awt.image.PackedColorModel.createCompatibleSampleModel ba:28 bp:298 bp:338 java.lang.Thread.run | java.lang.IllegalArgumentException: Width (0) and height (0) must be > 0

But it seems to collect all properties except for browser crap. It then spews out unrelated errors due to other code failing because of that code. I went on github and used couple different sources of loading rs into applet and they all getting same error message.

**Comment by ShivamMistry** [comment]
Should now be fixed in master, sorry it took so long!
